version: "3.9"
services:
  db:
    image: mysql:5.7
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: provinciasEC
      MYSQL_USER: user
      MYSQL_PASSWORD: 123456
    volumes:
      - ./provinciasEcuador.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"

  servidor1:
    build: ./servidor1
    environment:
      - DB_HOST=db
      - DB_USER=user
      - DB_PASSWORD=123456
      - DB_NAME=provinciasEC
      - SERVIDOR=Servidor 1
    depends_on:
      - db

  servidor2:
    build: ./servidor2
    environment:
      - DB_HOST=db
      - DB_USER=user
      - DB_PASSWORD=123456
      - DB_NAME=provinciasEC
      - SERVIDOR=Servidor 2
    depends_on:
      - db

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - servidor1
      - servidor2
